name: Automatic_Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Generating_Documentation:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Cache_doc
      id: cache-doc
      uses: actions/cache@v2
      with:
        path: temp-doc
        key: ${{ runner.os }}-doc
      
    - name: Change Directory 
      run: cd D:/a/Alis/Alis/ApiDoc
      
    - name: Show Directory 
      run: dir
      
    - name: Build Doc
      run: D:/a/Alis/Alis/ApiDoc/Doxygen/run/doxygen D:/a/Alis/Alis/ApiDoc/ApiDoc
    
    - name: Update web
      uses: EndBug/add-and-commit@v6 
      with:
        author_name: Automatic_Documentation
        author_email: pabloperdomofalcon@gmail.com
        message: 'Automatic commit of action'
        push:  true
        
