# Test the cross platform of Editor | Core | Tools
name: "Cross_Platform"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  job1: 
    name: Ubuntu
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Cache_Ubuntu
        id: cache-ubuntu
        uses: actions/cache@v2
        with:
          path: temp-ubuntu
          key: ${{ runner.os }}-ubuntu

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./Editor/Editor.csproj -p:PublishProfile=LinuxX64
        
        
  job2: 
    name: Windows
    runs-on: windows-2019
    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Cache_Windows
        id: cache-windows
        uses: actions/cache@v2
        with:
          path: temp-windows
          key: ${{ runner.os }}-windows   

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./Editor/Editor.csproj -p:PublishProfile=WindowsX64      
        
  job3: 
    name: MacOS
    runs-on: macos-10.15
    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Cache_MacOs
        id: cache-macos
        uses: actions/cache@v2
        with:
          path: temp-macos
          key: ${{ runner.os }}-macos   

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./Editor/Editor.csproj -p:PublishProfile=MacOSX64   
