# Test the cross platform of Editor | Core | Tools
name: "Cross_Platform"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  job1: 
    name: Test_On_Ubuntu
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Cache_Ubuntu
        id: cache-ubuntu
        uses: actions/cache@v2
        with:
          path: temp-ubuntu
          key: ${{ runner.os }}-ubuntu    
        
  job2: 
    name: Test_On_Windows
    runs-on: windows-2019
    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Cache_Windows
        id: cache-windows
        uses: actions/cache@v2
        with:
          path: temp-windows
          key: ${{ runner.os }}-windows      
        
  job3: 
    name: Test_On_MacOS
    runs-on: macos-10.15
    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Cache_MacOs
        id: cache-macos
        uses: actions/cache@v2
        with:
          path: temp-macos
          key: ${{ runner.os }}-macos    
