name: Publish Nugets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Nugets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Windows
    
    - name: Setup NuGet.exe for use with actions
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH:  ./Core/Core.csproj
        TAG_FORMAT: "*"
        VERSION_REGEX: "*"
        NUGET_KEY: ${{secrets.NUGET}}
